defaults: &defaults
  adapter: postgresql
  encoding: utf8
  username:
  password:
  template: template0 # Required for UTF8 encoding

development:
  <<: *defaults
  database: andrewmitchell_development
test: &TEST
  <<: *defaults
  database: andrewmitchell_test
  min_messages: WARNING
staging:
  <<: *defaults
  database: andrewmitchell_staging
production:
  <<: *defaults
  database: andrewmitchell_production